## Deploy Without Pipeline

In [5]:
import pickle
import numpy as np

In [15]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl', 'rb'))
clf = pickle.load(open('models/clf.pkl', 'rb'))

In [24]:
# assume we got some user input
# Pclass/gender/age/SibSp/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'], dtype=object).reshape(1,7)

In [30]:
test_input
# since this data has strings, you'll have to do all the preprocessing on this

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [31]:
test_input_sex = ohe_sex.transform(test_input[:, 1].reshape(1,1))

c:\Dev\Conda\envs\ds\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [39]:
test_input_sex
# encoded with 2 values for male and female

array([[0., 1.]])

In [36]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [50]:
test_input_embarked
# encoded with three values since there were 3 boarding stations

array([[0., 0., 1.]])

In [51]:
test_input_age = test_input[:,2].reshape(1,1)

In [52]:
test_input_transformed = np.concatenate((test_input[:, [0,3,4,5]], test_input_age, test_input_sex, test_input_embarked), axis=1)

In [53]:
test_input_transformed

array([[2, 0, 0, 10.5, 31.0, 0.0, 1.0, 0.0, 0.0, 1.0]], dtype=object)

In [55]:
clf.predict(test_input_transformed)

array([1], dtype=int64)

Looks like our passenger is gonna make it...

But note that we had to do a lot of stuff, if you were to do changes like this in production, it will take time. Pipelines make it easier for you, even if you make the changes in the pipeline, all you have to do is change the data and the processing will take care of the model.